[package]
name = "moe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
gloo = "0.8.0"
js-sys = "0.3.61"
once_cell = "1.17.1"
vodozemac = { version = "0.3.0", default-features = true, features = ["js"] }
#path = "../vodozemac"
wasm-bindgen = "0.2.84"
