on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2
        with:
          key: 'rust-cache'

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install wasm-bindgen
        working-directory: crates/moe
        run: |
          VERSION=$(cargo pkgid --frozen wasm-bindgen | cut -d "@" -f 2)
          cargo +stable install --version $VERSION wasm-bindgen-cli

      - run: npm install
      - run: npm run wasm

      # svelte-check
      - run: npm run check
      # pretter & eslint
      - run: npm run lint
      # Build
      - run: npm run build

      - name: Setup supabase CLI
        run: npm run supabase:start

      - name: Verify generated types match Postgres schema
        run: |
          supabase gen types typescript --local > schema.gen.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet schema.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - run: npx playwright install-deps
      - run: npx playwright install

      - name: setup web-push endpoint
        run: |
          DOCKER_ADDRESS=$(ip address show docker0 | grep -oP 'inet \K(\d{1,3}\.){3}\d{1,3}')
          nohup npm run preview -- --host $DOCKER_ADDRESS --port 5173 --strictPort &

      # run playwright tests
      - run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          key: 'rust-cache'

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install wasm-bindgen
        working-directory: crates/moe
        run: |
          VERSION=$(cargo pkgid --frozen wasm-bindgen | cut -d "@" -f 2)
          cargo +stable install --version $VERSION wasm-bindgen-cli

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # preview deployment
      - name: Pull Vercel Environment Information
        if: github.event_name == 'pull_request'
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: github.event_name == 'pull_request'
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        if: github.event_name == 'pull_request'
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      # production deployment
      - name: Pull Vercel Environment Information
        if: github.event_name == 'push'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: github.event_name == 'push'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        if: github.event_name == 'push'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
